# Generated by Django 2.2.2 on 2019-06-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Người Dùng', 'verbose_name_plural': 'Người Dùng'},
        ),
    ]
