# Generated by Django 2.2.7 on 2019-12-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/%Y/%m/%d/', verbose_name='Image:'),
        ),
    ]
