# Generated by Django 2.2.3 on 2019-08-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='kind',
            field=models.CharField(choices=[('windows', 'windows'), ('linux', 'linux'), ('technology', 'technology'), ('entertainment', 'entertainment')], default='entertainment', max_length=120, verbose_name='Kind:'),
        ),
    ]
