# Generated by Django 2.2.4 on 2019-09-08 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190810_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='like',
            field=models.IntegerField(default=0, editable=False, verbose_name='Like:'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Publish Date:'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='view_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Views:'),
        ),
    ]
